config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cars#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy, :edit, :update]
  resources :bookings, only: [:index, :show, :edit, :update]
  get '/bookings/:id/cancel', to: "bookings#cancel", as: 'cancel_booking'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user

  validates :start_time, :end_time, presence: true
  validates :car, :user, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  geocoded_by :address

  after_validation :geocode, if: :will_save_change_to_address?

  validates :model, :seats, :year, :colour, :address, :description, presence: true

  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_model_year_colour_and_address,
    against: [ :model, :year, :colour, :address],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :comment, presence: true
  validates :star, numericality: { greater_than: 0, less_than: 6 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # every user will need to be signed in before they can do a certain action.
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # add additional username to sign up and sign in
  def configure_permitted_parameters
    # new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :cancel]
  before_action :set_car, only: [:new, :create]

  def index
    @bookings = Booking.all
    @bookings = policy_scope(Booking)
  end

  def new
    @booking = Booking.new

    @car = Car.find(params[:car_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)

    @user = current_user

    @booking.user = @user
    @booking.car = @car

    authorize @booking

    @booking.cancelled = false
    if @booking.save!
      redirect_to booking_path(@booking), notice: "Booking was successfully created."
    else
      puts "=================NOT SAVING!!!!================="
      render :new
    end
    # TODO: may need to create conditional, for when Car is available or 'not booked'
  end

  def show
    @car = @booking.car
    @car_owner = @car.user


  end

  def edit; end

  def update
    # TODO: This is not currently working. Leads to /booking/:id
    authorize @booking
    if @booking.update(booking_params)
      redirect_to booking_path(@booking), notice: "Booking was successfully edited."
    else
      puts "=================NOT SAVING!!!!================="
      render :edit
    end
  end

  # def destroy
  #   @booking.destroy

  #   # Currently redirects to cars_path (index of all the cars)
  #   redirect_to cars_path
  # end

  def cancel
    @booking.cancelled = true

    authorize @booking

    # this is returning a booking with cancelled = true

    # booking params is failing = param is missing or the value is empty:booking
    if @booking.save(cancel_params)
      redirect_to bookings_path(@booking), notice: "booking was successfully cancelled"
    else
      render :show, notice: "unable to cancel booking, please contact host"
    end
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :cancelled)
  end

  def cancel_params
    params.permit(:start_time, :end_time, :cancelled)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @cars = policy_scope(Car)

    if params[:query].present?
      # sql_query = " \
      #   cars.address @@ :query \
      #   OR cars.model @@ :query \
      #   OR cars.colour @@ :query \
      #   OR cars.year @@ :query \
      # "
      # @cars = Car.where(sql_query, query: "%#{params[:query]}%")
      @show_map = true
      @cars = Car.search_by_model_year_colour_and_address(params[:query])
    else
      @show_map = false
      @cars = Car.all
    end

    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window: render_to_string(partial: "info_window", locals: { car: car }),
        image_url: helpers.asset_path('hero-car.png')
      }
    end
  end

  def show
    @user = @car.user

    @bookings = @car.bookings

    @reviews = Review.all

    @show_review_button = false
    @bookings.each do |booking|
      if booking.user == current_user
        @show_review_button = true
      end
    end

    @booking = Booking.new
    authorize @booking
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    authorize @car

    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit; end

  def update
    @car.update(car_params)

    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def destroy
    @car.destroy

    redirect_to cars_path
  end

  private

  def set_car
    @car = Car.find(params[:id])
    authorize @car
  end

  def car_params
    params.require(:car).permit(:model, :seats, :year, :colour, :address,
                                :price, :image_one, :image_two, :image_three,
                                :photo, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_car, only: [:new, :create]
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :authorize_review, only: [:edit, :update, :destroy]
  before_action :set_car_id, only: [:update, :destroy]

  def new
    @review = Review.new

    authorize @review
  end

  def create
    @review = Review.new(review_params)

    @review.user = current_user


    authorize @review

    @review.car_id = @car.id

    if @review.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit; end

  def update

    if @review.update(review_params)
      redirect_to car_path(@car)
    else
      render :edit
    end
  end

  def destroy
    @review.destroy

    redirect_to car_path(@car)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :star)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_car
    @car = Car.find(params[:car_id])
  end

  def authorize_review
    authorize @review
  end

  def set_car_id
    @car = @review.car_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <div class="card shadow rounded p-4">
        <h1 class="ml-4 mt-3 fugaz-font">Update your booking</h1>
        <div class="form ml-4">
          <%= simple_form_for([@car, @booking] ) do |f| %>
          <div class="form-group">
            <%= f.input :start_time, as: :date, html5: true, label: "Start Date", required: false %>
            <%= f.input :end_time, as: :date, html5: true, label: "End Date", required: false %>
            <%= f.button :submit, "Update Booking", class: 'btn btn-outline-dark ml-1' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>  
</div>  

app/views/bookings/index.html.erb
<div class="container">
    <h1 class="ml-4" style="margin-left: 80px; font-family: Fugaz One;">Bookings</h1>
    <% if policy(@bookings).index? %>
    <div class="row d-flex">
      <% @bookings.each do |booking| %>
        <% if booking.user == current_user %>
          <% car = booking.car %>
          <% car_owner = car.user %>
          <div class="col-4 p-5">
            <div class="card shadow ">
              <%= cl_image_tag car.photo.key, :class => "card-img-top mark-card-image" %>
                <div class="card-body">
                  <h5 class="card-title fugaz-font"><%= car.model %></h5>
                  <p class="card-text font-italic" style="height: 50px;"><%= car.address %></p>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">Year: <%= car.year %></li>
                  <li class="list-group-item">Colour: <%= car.colour %></li>
                  <li class="list-group-item">£<%= car.price %> / day</li>
                <% if booking.cancelled == true %>
                  </ul>
                  <h2 class="list-group-item fugaz-font p-4" style="border: none;"> Booking Cancelled</h2>
                <% else %>
                  <li class="list-group-item" style="border: none">Booking Period: <%= booking.start_time.strftime("%-d/%-m/%Y") %> to <%= booking.end_time.strftime("%-d/%-m/%Y") %></li>
                <% end %>
                </ul>
                  <div class="card-body d-flex justfiy-content-between">
                <% unless booking.cancelled == true %>
                    <a href="#" class="card-link"><%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-outline-secondary mr-2" %></a>
                    <a href="#" class="card-link"><%= link_to 'Cancel',
                                                cancel_booking_path(booking),
                                                class: "btn btn-outline-secondary mr-2",
                                                data: {confirm: 'Are you sure you want to cancel this booking?'} %></a>
                    <a href="#" class="card-link"><%= link_to 'View', car_path(car), class: "btn btn-outline-secondary" %></a>
                 <% end %>
                  </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <% end %>
  </div>

app/views/bookings/new.html.erb
<div class="container">
  <h1 class="form-text">book this car!</h1>
  <div class="container form">
    <%= simple_form_for([@car, @booking] ) do |f| %>
      <%= f.input :start_time, as: :date, html5: true %>
      <%= f.input :end_time, as: :date, html5: true %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row align-self-center justify-content-center">
    <div class="col-4 mb-4">
      <div style="background-color: white; padding: 12px; border-top-left-radius: 8px; border-top-right-radius: 8px;">
        <h2 class="fugaz-font" style="font-size: 36px;">Booking Success!</h2>
        <h5>You have just booked <%= @car.model %></h5>
      </div>
      <div class="card shadow"  style="border: none">
        <%= cl_image_tag @car.photo.key, :class => "card-img-top mark-card-image" %>
        <div class="card-body">
          <h5 class="card-title fugaz-font"><%= @car.model %></h5>
          <p class="card-text"><%= @car.address %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item" style="border: none">Year: <%= @car.year %></li>
          <li class="list-group-item" style="border: none">Colour: <%= @car.colour %></li>
          <li class="list-group-item" style="border: none">Booking Period: <%= @booking.start_time.strftime("%-d/%-m/%Y") %> to <%= @booking.end_time.strftime("%-d/%-m/%Y") %></li>
        </ul>
        <div class="card-body d-flex" style="border: none">
          <a href="#" class="card-link"><%= link_to 'Edit', edit_booking_path(@booking), class: "btn btn-outline-secondary mr-1" %></a>
          <a href="#" class="card-ling"><%= link_to 'Cancel',
                                              cancel_booking_path(@booking),
                                              class: "btn btn-outline-secondary mr-1",
                                              data: {confirm: 'Are you sure you want to cancel this booking?'} %></a>
          <a href="#" class="card-link"><%= link_to 'View', car_path(@car), class: "btn btn-outline-secondary" %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cars/_info_window.html.erb
<% user = car.user %>
<div class="card">
  <%= cl_image_tag car.photo.key %>
  <div class="card-body">
    <h5 class="card-title fugaz-font"><%= car.model %></h5>
    <p class="card-text"><%= car.address %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">£<%= car.price %> / day</li>
  </ul>
  <a href="#" style="width: 50px;"><%= link_to 'More info', car, :class => "btn btn-outline-dark" %></a> 
</div>

app/views/cars/create.js.erb
var reviews = document.querySelector("#reviews");
users.insertAdjacentHTML("beforeend", "<%= j render(@review) %>");

app/views/cars/edit.html.erb
<div class="container">
  <div class="add-car-form shadow rounded">
    <h1 class="fugaz-font m-3" style="font-size: 24px; text-align: center;">Edit your car</h1>
    <%= simple_form_for(@car) do |f| %>
    <div class="row">
      <div class="col">
      <%= f.input :model, required: false %>
      
      </div>
      <div class="col">
      <%= f.input :year, required: false %>
      </div>
    </div>
    <div class="row">
      <div class="col">
      <%= f.input :seats, required: false %>
      </div>
      <div class="col">
      <%= f.input :colour, required: false %>
      </div>
    </div>
      <%= f.input :address, required: false %>
      <%= f.input :price, required: false %>
      <%= f.input :description, required: false %>
    <div class="row">
      <div class="col d-flex justify-content-start">
      <%= f.input :photo, as: :file %>
      </div>
      <div class="col d-flex justify-content-end">
      <%= f.submit "Update Car", class: "btn btn-outline-dark add-car-button mt-4" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cars/index.html.erb
  <% if @show_map %>
  <div class="d-flex align-items-baseline">
    <h1 style="margin-left: 80px; font-family: Fugaz One;">Cars</h1>
    <p class="ml-1">we found <strong><%= @cars.count %></strong> that match your search</p>
  </div>
  <div class="main-container-map-index">
    <div class="cards-map-index">
      <% @cars.each do |car| %>
      <div class="card shadow">
          <%= cl_image_tag car.photo.key, :class => "card-img-top mark-card-image" %>
          <div class="card-body pb-0">
            <% if car.model.length < 16 %>
              <h5 class="card-title text-center" style="font-size: 32px; font-family: Fugaz One;"><%= car.model %></h5>
            <% else %>
              <h5 class="card-title text-center" style="font-size: 24px; font-family: Fugaz One;"><%= car.model %></h5>
            <% end %>
          </div>
          <div class="mx-2 d-flex align-items-center justify-content-between">
            <ul class="list-group list-group-flush">
              <li class="list-group-item" style="font-family: 'Open Sans', sans-serif;"><%= car.city %></li>
              <li class="list-group-item" style="font-family: 'Open Sans', sans-serif;">Year: <%= car.year %></li>
              <li class="list-group-item" style="font-family: 'Open Sans', sans-serif;">£<%= car.price %> / day</li>
            </ul>
            <a href="#" class="card-link"><%= link_to 'More info', car, :class => "btn btn-outline-dark" %></a>
          </div>
        </div>
      <% end %>
    </div>
    <div id="map"
      style="width: 100%; height: 100vh; position: sticky; top: 100px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

  <% else %>
  <% content_for :navbar do %>
      <%= render './components/navbar2' %>
  <% end %>

  <div class="container-fluid" style="margin-top: -90px;">
  <div class="hero-container">
    <div class="hero-text">
      <h1>classicar</h1>
      <p>Find the car of your dreams.</p>
      <p>Cruise in style.</p>
    </div>
  </div>

  <hr style="color: gray; margin: 40px 80px 20px 80px;">

  <div class="container">
  <h1 class="ml-4" style="margin-left: 80px; font-family: Fugaz One;">Cars</h1>
  <%= link_to "Add car", new_car_path, :class => "btn btn-dark ml-4" %>
  <div class="row d-flex">
    <% @cars.each do |car| %>
      <div class="col-4 p-5" id="fade">
        <div class="card shadow">
          <%= cl_image_tag car.photo.key, :class => "card-img-top mark-card-image" %>
          <div class="card-body">
            <% if car.model.length < 16 %>
              <h5 class="card-title text-center" style="font-size: 32px; font-family: Fugaz One; height: 50px;"><%= car.model %></h5>
            <% else %>
              <h5 class="card-title text-center" style="font-size: 24px; font-family: Fugaz One; height: 50px;"><%= car.model %></h5>
            <% end %>
          </div>
          <div class="mx-5 d-flex align-items-center justify-content-between">
            <ul class="list-group list-group-flush pb-2">
              <li class="list-group-item"><%= car.city %></li>
              <li class="list-group-item">Year: <%= car.year %></li>
              <li class="list-group-item">£<%= car.price %> / day</li>
            </ul>
            <a href="#" class="card-link"><%= link_to 'More info', car, :class => "btn btn-outline-dark" %></a>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<div class="container">
  <div class="add-car-form shadow rounded">
    <h1 class="fugaz-font m-3" style="font-size: 24px; text-align: center;">Add your car</h1>
    <%= simple_form_for(@car) do |f| %>
    <div class="row">
      <div class="col">
      <%= f.input :model, required: false %>
      
      </div>
      <div class="col">
      <%= f.input :year, required: false %>
      </div>
    </div>
    <div class="row">
      <div class="col">
      <%= f.input :seats, required: false %>
      </div>
      <div class="col">
      <%= f.input :colour, required: false %>
      </div>
    </div>
      <%= f.input :address, required: false %>
      <%= f.input :price, required: false %>
      <%= f.input :description, required: false %>
    <div class="row">
      <div class="col d-flex justify-content-start">
      <%= f.input :photo, as: :file %>
      </div>
      <div class="col d-flex justify-content-end">
      <%= f.submit "Create Car", class: "btn btn-outline-dark add-car-button mt-4" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h2 class="show-viewing-title">You are viewing <span class="font-italic fugaz-font"><%= @car.model %></span></h2>
  </div>
  <div class="row">
    <div class="col-8">
      <div class="card shadow rounded">
          <div class="card-horizontal">
              <div class="img-square-wrapper align-self-center">
                <%= cl_image_tag(@car.photo.key, :width => 500, :crop => "pad") %>
              </div>
              <div class="card-body">
                  <h4 class="card-title"><%= @car.model %></h4>
                  <ul class="list-group list-group-flush ul-no-pad">
                    <li class="list-group-item">Year: <%= @car.year %></li>
                    <li class="list-group-item">Colour: <%= @car.colour %></li>
                    <li class="list-group-item">Address: <%= @car.address %></li>
                    <li class="list-group-item">£<%= @car.price %> / day</li>
                    <li class="list-group-item">description</li>
                    <li class="list-group-item"><%= @car.description %></li>
                  </ul>

                    <% if policy(@car).destroy? %>
                      <a href="#" class="card-link"><%= link_to 'edit car', edit_car_path(@car), class: "btn btn-outline-dark" %></a>
                      <a href="#" class="card-link"><%= link_to 'delete car',
                                                                car_path(@car),
                                                                method: :delete,
                                                                class: "btn btn-outline-dark",
                                                                data: { confirm: 'Are you sure you want to delete this car?'} %></a>
                    <% end %>
              </div>
          </div>
          <div class="card-footer d-flex justify-content-between">
            <small class="text-muted">Owner: <%= @user.username %></small>
            <div>
              <% if @show_review_button %>
                <a href="#" class="card-link"><%= link_to 'add review', new_car_review_path(@car), class: "btn btn-outline-dark" %></a>
              <% end %>
            </div>
          </div>
          <div>
            <% @reviews.each do |review| %>
              <% if @car.id == review.car_id %>
                <h2 class="mt-2 pl-3 review-comment"><%= review.comment %> - <span class="font-weight-bold"><%= review.user.username %></span></h2>
                <h5 class="pl-3"><%= image_tag('car-wheel.svg', class: "wheel-image") * review.star %></h5>
                <% if review.user_id == current_user %>
                  <a href=""><%= link_to 'edit', edit_review_path(review) %></a>
                  <a href=""><%= link_to 'delete', review_path(review),
                                                   method: :delete,
                                                   data: { confirm: 'Are you sure
                                                    you want to delete review?'} %></a>
                <% end %>
              <% end %>
            <% end %>
          </div>
      </div>
    </div>
  <% unless @current_user == @user %>

    <div class="col-4">
      <div class="card shadow rounded p-4" style="position: sticky; top: 100px;">
        <h1 class="ml-4 mt-3 fugaz-font">book this car!</h1>
        <div class="form ml-4">
          <%= simple_form_for([@car, @booking] ) do |f| %>
          <div class="form-group">
            <%= f.input :start_time, as: :date, html5: true, label: "Start Date", required: false %>
            <%= f.input :end_time, as: :date, html5: true, label: "End Date", required: false %>
            <%= f.button :submit, "Create Booking", class: 'btn btn-outline-dark ml-1' %>
            </div>
          <% end %>
        </div>
      </div>
  <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classicar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Fugaz+One&family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <script src="https://unpkg.com/scrollreveal"></script>
    <script>
        ScrollReveal({ reset: true });
    </script>
  </head>

  <body>
    <div class="container-fluid" style="margin-top: 100px; padding: 0;">
      <p hidden class="notice"><%= notice %></p>
      <p hidden class="alert"><%= alert %></p>
      <% if content_for(:navbar) %>
        <%= render './components/navbar2' %>
      <% else %>
        <%= render './components/navbar' %>
      <% end -%>
      <%= yield %>
      <%= render './components/footer' %>
    </div>
  </body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/edit.html.erb
<div class="container">
  <h1 class="form-text">review</h1>
  <div class="container form">
    <%= simple_form_for([@car, @review] ) do |f| %>
      <%= f.input :comment %>
      <%= f.input :star%>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="review-form-container shadow rounded">
  <h1 class="fugaz-font larger" style="font-size: 24px;">Leave a review!</h1>
  <div class="form">
    <%= simple_form_for([@car, @review] ) do |f| %>
      <%= f.input :comment, required: false %>
      <%= f.input :star, collection: (1..5).to_a, label: "Rate your experience" %>
      <%= f.button :submit, "Post Review", class: 'btn btn-outline-dark' %>
    <% end %>
  </div>
</div>